### PR TITLE
[#7795] reduce unnecessary applications.pinpoint request from web UI

### PR DESCRIPTION
**Pull request by yjqg6666**
Remove unnecessary applications.pinpoint request on the following pages:
1. transaction list page
2. transaction view page
3. transaction detail page
4. filtered map page
5. browser not support page
6. scatter full screen mode page

The first four pages are the most-visited pages. Opt the request out should boot the page loading.

### CODE REVIEW

**Comment by yjqg6666** [comment]
@binDongKim PTAL.

**Comment by binDongKim** [comment]
Your suggestion is reasonable so I've tried your approach but there was one thing I need to resolve.

We navigate to other pages with a new tab in most cases except the "config page". In this case, if I put the application resolver in the child route like you did, the application api call would keep requested when navigating to the config page and the main page back and forth. 

So I will think about the solution for the above issue first and then when it gets resolved, I will take your approach.
Many thanks.

**Comment by yjqg6666** [comment]
@binDongKim The config page will still request the api, since in some child pages the data is still needed. The first 4 pages are the most-wanted, so i kept the config pages untouched. If needed, the resolver for config children pages should be enumerated.

**Comment by binDongKim** [comment]
Yeah I know. But I mean, users go to the config page and back to the main page back and forth and the api would be request repeatedly which causes the time longer. But I get your point.

**Comment by yjqg6666** [comment]
Now i get your point.

**Pull request closed without merging**
