### PR TITLE
2.2.x

### PR DESCRIPTION
**Pull request by zhangyinhao1234**
添加了一个sdk，用来创建线程池，和创建runable，参考Spring的Async的实现方式，使用自己创建的runable和线程池实现了多线程链路的显示，原来这块在代码在1.8.3版本上运行，已经稳定运行1年。

### CODE REVIEW

**Comment by zhangyinhao1234** [comment]
example：

    private ThreadPoolExecutor triggerPool = new AsyncThreadPoolExecutor(
            32,
            256,
            60L,
            TimeUnit.SECONDS,
            new LinkedBlockingQueue<Runnable>(1000));

    
    @GetMapping("/hello1")
    public String test11(String name) throws InterruptedException {
        String hello = helloService.hello();
        triggerPool.execute(new AsyncRun() {
            @Override
            public Object asyncRun() {
                String pp = helloService.hello2(name, "PP");
                return pp;
            }
        }.getRunnable());
        return hello;
    }

**Comment by zhangyinhao1234** [comment]
日志中未发现提示错误的地方。。不清楚哪里出了错

**Comment by emeroad** [comment]
Please use English.

If there is a lot of log output from travis, the build will fail.

Could you push PR to master branch.
The master branch uses github action, so there is no such problem.

**Comment by zlp1992** [comment]
@zhangyinhao1234 @emeroad  what's the difference between `pinpoint-java-sdk` and the existed `thread `plugin(since Pinpoint 2.0.2) ? I think the purpose of both is same, just to keep tracing in aysnc thread. Using `thread `plugin we don't have to modify business application, while using `pinpoint-java-sdk` we have to modify our business application to support async trace  (for example, use `AsyncRun` in our code) ?

**Comment by emeroad** [comment]
The thread-plugin operates on global state, making it difficult to limit specific targets.
On the other hand, SDK can also have high accuracy.

For example, SDK makes it very easy to select a specific action when there are multiple asynchronous actions in a method.

**Comment by zlp1992** [comment]
Get it. But using SDK we will have to modify our application code ?

**Pull request closed without merging**
