### PR TITLE
Support collect detailed exception stacktrace by config

### PR DESCRIPTION
**Pull request by IluckySi**
Support collect detailed exception stacktrace by config
⁣related to  #7158

### CODE REVIEW

**Comment by IluckySi** [comment]
@emeroad Hello，Woonduk~ Do you think there is any problem with this？ Thank you~

**Comment by emeroad** [comment]
Could you give me the `Allow edits from maintainers` permission?

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by IluckySi** [comment]
> Could you give me the `Allow edits from maintainers` permission?
> 
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork


Why I can not see “Allow edits from maintainers” option in https://github.com/naver/pinpoint/pull/7255

image

**Comment by IluckySi** [comment]
new pr：https://github.com/pinpoint-apm/pinpoint/pull/7736

**Pull request closed without merging**
