### PR TITLE
add rocketmq plugin

### PR DESCRIPTION
**Pull request by chengruyi**
add rocketmq plugin

### CODE REVIEW

**Comment by Xylus** [comment]
@ruizlake Thanks for contribution. A few things - Looks like you're missing a *.gitignore* file for your plugin and all the class files and bin files are getting committed. Could you add a *.gitignore* file for your plugin? You can simply copy and paste the file from [here](https://github.com/naver/pinpoint/blob/master/plugins/activemq-client/.gitignore) to the root of rocketmq plugin.
There also seems to be some conflicts. Could you resolve them and rebase against the master and push again?
Thanks!

**Comment by ruizlake** [comment]
I am really sorry for the late reply！i have added  a .gitignore file in my plugin

**Comment by Xylus** [comment]
@ruizlake Thanks for the fix, but now it looks like the branch has conflicts.
Could you resolve these and rebase the branch to the latest master?

**Comment by Xylus** [comment]
@ruizlake 
Hi ruizlake, we're preparing to release 1.6.0 soon and would like to get this one merged. Could you resolve the conflict so we can get it merged to master?

This might help resolve the conflict would be (**please ignore this if you already know**) :

1. In your master branch, do `git reset --hard e9b544a`  
  This will undo your [last commit](https://github.com/ruizlake/pinpoint/commit/2b499423913b2d11ba5ccf6c2d0b15a602dadd7a) that has the unwanted merge. (Make sure your working directory is clean so that you don't lose anything that is not committed)
2. Do `git reset --soft 3ffd35c`  
  This will reset your master's HEAD to before you've implemented rocketmq plugin, but will leave your rocketmq plugin code still intact and staged. This is mainly done to move the changes you've made to a feature branch instead of master.
3. Do `git checkout -b feature/issue-1942` (branch name doesn't really matter)  
  This will move your current branch to *feature/issue-1942* so you don't have to commit your plugin code to master. This makes updating your master later very simple.
4. Commit your plugin code to *feature/issue-1942* branch

After the steps above, your rocketmq plugin code should all be committed to *feature/issue-1942* branch and be isolated from master so you can update your master branch to the latest. Follow the next steps to rebase your commit to the latest master + push + make a pull request.

5. Do `git checkout master`  
  You will once again be back at master with your working directory clean.
6. Do `git fetch upstream`, then `git merge upstream/master` (or whatever you've named the naver/pinpoint repository)  
  This will update your master branch to the latest version from naver/pinpoint (You can use `pull` instead). If you haven't set up a remote repository for naver/pinpoint, take a look [here](https://help.github.com/articles/configuring-a-remote-for-a-fork/#platform-windows) to set one up.
7. Once your master is up to date, do `git rebase master feature/issue-1942`  
  This will now rebase the rocketmq commit you've made onto your updated master branch. There might be conflicts during the rebase - if there are, resolve all the conflicts and do `git rebase --continue` to continue and complete the rebase. You will also now be in *feature/issue-1942* branch.
8. Test our your plugin and see if it works correctly.
9. Do `git push origin feature/issue-1942`  
  Your rocketmq plugin commit will be pushed to your fork under the *feature/issue-1942* branch.
10. Create a pull-request from your fork's *feature/issue-1942*

Please let me know if you run into any problems.
Thanks!

**Comment by ld000** [comment]
Is this plugin still on working?

**Comment by tank1314** [comment]
Why is the value empty when Trace trace = traceContext.currentTraceObject (); in RocketMQMessageProducerSendInterceptor ?

**Comment by biezhi** [comment]
@chengruyi Are you still paying attention to this pr?

**Comment by yjqg6666** [comment]
Any update for this? @chengruyi

**Comment by koo-taejin** [comment]
I close this issue, becuase it is resolved via #7529 PR.

**Pull request closed without merging**
