### PR TITLE
[#7962] record configured response header

### PR DESCRIPTION
**Pull request by yjqg6666**
## Feature
Record response header on server/client side.

## Configuration
profiler.http.record.response.headers=Connection,Location,ExternalTraceid,Set-Cookie

Set the config value to _**HEADERS-ALL**_  to record all of the response headers from server/client side.

### Server Side
**Plugin        Implemented         Tested**  
Jetty                 Yes                    Yes  
Tomcat             Yes                    Yes  
Reactor-netty    Yes                    Yes
Undertow           Yes                    Yes   
Jboss                 Yes                    No  
Resin                 Yes                    No
Weblogic            No                      No
Websphere         No                      No

Note: _If the feature for Weblogic & Websphere plugins had been implemented_, the status code recorder can be removed from the ServletRequestListener completely and currently is kept for compatibility.

### Client Side
**Plugin        Implemented         Tested**
httpclient4         Yes                       Yes
httpclient3          Yes                       Yes
okhttp                  Yes                      Yes
okhttp3                 Yes                      Yes
jdk http                Yes                        Yes
resttemplate        Yes                      Yes
webflux                Yes                      Yes
reactor-netty        Yes                       Yes

## Demo

Configured header occurred once:

image

Configured header occurred multiple times:
image

Configured header applied on client side:
image

Async request:
image

## Additional changes
1. Move response status recorder to ServletResponseListener.
2. ~~Extract the common interface methods of SpanRecorder and SpanEventRecorder to SpanCommonRecorder~~. Extract the recordAttribute interface methods of SpanRecorder and SpanEventRecorder to AttributeRecorder.

### CODE REVIEW

**Comment by yjqg6666** [comment]
@emeroad PTAL and looking forward to your advice.

**Comment by yjqg6666** [comment]
Rebased on the current master.

**Comment by emeroad** [comment]
@yjqg6666 :+1: 
It seems to be a very useful feature.

I will merge in 2.3.1

**Comment by yjqg6666** [comment]
I will add more commits for recording response header on http client side and still working on it.

**Comment by yjqg6666** [comment]
Work on the client side is done.

**Comment by linxu163** [comment]
> @yjqg6666 👍
> It seems to be a very useful feature.
> 
> I will merge in 2.3.1

@emeroad When will 2.3.1 be released? and will it support to record request header? I need this feature to get mapping with our internal monitoring system. Thank you!

**Comment by yjqg6666** [comment]
@linxu163 Recording request header feature has already been available since version 2.1.0. You may check the release note:
https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.1.0 under section "Record request header & cookie" and the related PR is #6897 if you are interested.

**Comment by linxu163** [comment]
> @linxu163 Recording request header feature has already been available since version 2.1.0. You may check the release note:
> https://github.com/pinpoint-apm/pinpoint/releases/tag/v2.1.0 under section "Record request header & cookie" and the related PR is #6897 if you are interested.

@yjqg6666 Thank you so much! I would enable it right now

**Comment by yjqg6666** [comment]
For JDK HttpUrlConnection reading response header will cause the output stream closed, so we need to read response header only when the getInputStream is being intercepted.

**Comment by yjqg6666** [comment]
This PR contains bugfix for #8019 for recording https call made by jdk http client.

**Comment by yjqg6666** [comment]
Set the config value to HEADERS-ALL to record all of the response headers from server/client side.

**Comment by yjqg6666** [comment]
Rebased on the current master (2.3.1-snapshot).

**Pull request merged**
