### PR TITLE
[#7788] Agent name support

### PR DESCRIPTION
**Pull request by yjqg6666**
### Changes made are:
1.  Agent part, Read -Dpinpoint.agentName / command argument --agentName / environment variable PINPOINT_AGENT_NAME as agent name. Record agent name as a field of agent information.

2. Collector part, save agent name in agent information. 

3. Web part, Show agent name in pinpoint web pages (fetch agent name in agent information by agent id). 

4. Common part, refactoring rename AGENT_NAME_MAX_LEN to AGENT_ID_MAX_LEN in PinpointConstants / HbaseTableConstants / TraceRowKeyEncoderV2 / TraceRowKeyDecoderV2 to avoid confusion.

### Changes comparing to #7752:
1. rebased on master
2. squashed the commits and discard the finally-unnecessary commit/changes.

### The changes to UI are illustrated as follows:

1.  server list:

image

image

2.  inspector:

image

3.  transaction list:

image

4.  link filter wizard

image

5.  node filter wizard

image

### CODE REVIEW

**Comment by emeroad** [comment]
Thank you for your contribution.

This PR is very good.
I didn't find any issues with this code.

Could you create an issue and organize it?
It will be of great help when organizing the release notes.

**Comment by yjqg6666** [comment]
Just updated the commit messages to link to the related issue.

**Comment by yjqg6666** [comment]
Update: show agent name in transaction filter wizard.
Feature:
1. link filter wizard
image
2. node filter wizard
image

**Comment by yjqg6666** [comment]
When i complete the previous updated feature, i found the issue #7791, that should also be checked. They have some connection.

**Comment by yjqg6666** [comment]
Update: refactoring, rename AGENT_NAME_MAX_LEN to AGENT_ID_MAX_LEN in the HbaseTableConstants.java in commons-hbase module to avoid confusion.

**Comment by yjqg6666** [comment]
Nothing changed, rebase to change the commit hash to retrigger "Check Actions".

**Comment by yjqg6666** [comment]
@emeroad I randomly got check failed on unrelated tests.

> Error:  Errors: 
> Error:    ClusterTest.setUp:96 » Channel Failed to bind to: /10.1.0.156:35144
> Error:    ZookeeperClusterTest.clusterTest1:100->createPath:272 » ConnectionLoss KeeperE...
> Error:    ZookeeperClusterTest.clusterTest2:142->createPath:272 » ConnectionLoss KeeperE...

> Error:  com.navercorp.pinpoint.web.cluster.ClusterTest  Time elapsed: 1.428 s  <<< ERROR!
> org.jboss.netty.channel.ChannelException: Failed to bind to: /10.1.0.156:35144
> 	at com.navercorp.pinpoint.web.cluster.ClusterTest.setUp(ClusterTest.java:96)
> Caused by: java.net.BindException: Cannot assign requested address

The ip/port may be unavailable.

**Pull request merged**
