### PR TITLE
Add Elasticsearch Client bboss plugin

### PR DESCRIPTION
**Pull request by yin-bp**
Title: Elasticsearch Client Plugin Contribution

Link: https://github.com/bbossgroups/pinpoint/tree/elasticsearch-plugin/plugins/elasticsearch-bboss
Target: Elasticsearch Rest Client BBoss
Supported Version: pinpoint 1.9.0
Description: This agent plugin is worked with elasticsearch rest client BBoss,BBoss is a best Java Highlevel Rest client for ElasticSearch.

ServiceTypes: [9201, "ElasticsearchBBoss"],[9202, "ElasticsearchBBossExecutor"]
Annotations: [971, "es.args"],[972, "es.url"],[973, "es.dsl"],[974, "es.action"],[975, "es.responseHandle"],[976, "es.version"]

Configurations: List of configuration keys and description the plugin adds.

profiler.elasticsearchbboss.enabled=true //enable or disable this plugin, default true.
profiler.elasticsearchbboss.recordResult=false //record or disable record method return value ,default false.
profiler.elasticsearchbboss.recordArgs=true //record or disable record method args,default true.
profiler.elasticsearchbboss.recordDsl=true //record or disable record dsl,default true.
profiler.elasticsearchbboss.recordESVersion=true //record or disable record ES Version infomation,default true.
profiler.elasticsearchbboss.recordResponseHandlerClass=false //record or disable record response handle class ,default false.
profiler.elasticsearchbboss.maxDslSize=50000 //set the max length dsl script,over this size dsl will be substring.

### CODE REVIEW

**Comment by yin-bp** [comment]
Hi,@RoySRose 
A clean PR was added!

**Comment by RoySRose** [comment]
@yin-bp

Great Job.

0. I don't really see any problems in the logic for now. I'll also request reviews to my colleagues.
1. Please change the name of service types under ElasticSearchConstants.
ServiceTypes are shared through all Pinpoint Module(Web, Collector ...) 
words in service types to change from `Elasticsearch` to `ElasticsearchBBoss` would be enough
2. About `ElasticsearchExecutorIT` Test. This fails for now.
Integration Test with embedded Elasticsearch such as https://github.com/allegro/embedded-elasticsearch would be great. You can look at `MongoDBIT_3_7_x_IT.java` as an example. The test result of this *IntegrationTest* is applied to [Homepage](https://naver.github.io/pinpoint/main.html#supported-modules) automatically. So I strongly recommend to get it correctly.
3. Do you have any example app for me to test with? I remember there was some in the past, and I kind of modified it to test and getting errors. So if you have any updated example. Please let me know :)

**Comment by yin-bp** [comment]
@RoySRose :
here is a bboss web demo base spring boot and elasticsearch 5.x,6.x:
https://github.com/bbossgroups/es_bboss_web

**Comment by yin-bp** [comment]
@RoySRose 
Integration tests fail by adopting embedded elasticsearch. See continuous-integration/travis-ci/pr detail,how to handle errors in integration tests

**Comment by RoySRose** [comment]
@yin-bp 

Does Elasticsearch-bboss support jdk6?

**Comment by RoySRose** [comment]
@yin-bp 

Actually, there isn't any problem with the existing test code.
I've looked up to find the reason and embedded-elasticsearch doesn't support JDK6.
So I've made a new sub-module for Integration Test with JDK8 (agent-it8)

I've merged PR #5596 to the master.
You can see the changes by rebasing your branch with master.

I've modified `//TODO just a sample` part, just to stop generating test fails.

I think it will be wise to version 5.x of elasticsearch rather than 6.3.0. 
I don't know why but. 6.3.0 take so long to come up compared to 5.x(If you can find a better one~ please do)

Let me know when you're done

**Comment by yin-bp** [comment]
@RoySRose 
image
How can I rebasing my branch with pinpoint master?
Use the method above image, Other commits will be include in my branch.

**Comment by RoySRose** [comment]
Hello, @yin-bp Please check here https://blog.algolia.com/master-git-rebase/ this kindly explains about the rebase I was talking about. I use few tools such as sourcetree to easily manage git operations.
https://blog.algolia.com/wp-content/uploads/2017/12/image1.png this image shows most simplified version of what I'm talking about.

**Comment by yin-bp** [comment]
> @yin-bp
> 
> Does Elasticsearch-bboss support jdk6?

Do not support jdk 6,must be jdk 7 and upper.

**Pull request closed without merging**
