### PR TITLE
[#noissue] Add SpringSmtpMailSender Unit Test

### PR DESCRIPTION
**Pull request by imbf**
case 1 : Constructor requireNonNull Test.
case 2 : When Sender Email Address is not configured, Constructor throw NullPointerException.
case 3 : When Sender Email Address is wrong, Constructor throw RuntimeException.
case 4 : When receiver does not exist, do not send email
case 5 : When receiver is wrong, do not send email
case 6 : send Email with AlarmChecker
case 7 : send Email with AgentChecker

### CODE REVIEW

**Comment by minwoo-jung** [comment]
I will review soon.

**Comment by imbf** [comment]
if you don't mind, may i ask for a review?

**Comment by minwoo-jung** [comment]
@imbf
Sorry for the late confirmation. LGTM

**Comment by imbf** [comment]
Thank you @minwoo-jung

**Pull request merged**
